import "./CustomerJoinDetails.css";
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import type { ChangeEvent, SyntheticEvent } from "react";
import Header from "../../../components/Header/Header";
import QueueConfirmationModal from "../../../components/QueueConfirmation/QueueConfirmationModal";

function CustomerJoinDetails() {
  const navigate = useNavigate();
  const location = useLocation();

  // Queue code passed from the previous page.
  const queueCode = location.state?.queueCode;

  const [phoneNumber, setPhoneNumber] = useState("");
  const [showConfirmation, setShowConfirmation] = useState(false);
  const [ticketNumber, setTicketNumber] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isDemo, setIsDemo] = useState(false);

  const formatPhoneNumber = (value: string) => {
    const digits = value.replace(/\D/g, "").slice(0, 10);

    if (digits.length === 0) {
      return "";
    }

    if (digits.length <= 3) {
      return `(${digits}`;
    }

    if (digits.length <= 6) {
      return `(${digits.slice(0, 3)}) ${digits.slice(3)}`;
    }

    return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
  };

  const handlePhoneChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPhoneNumber(formatPhoneNumber(e.target.value));
  };

  const handleContinue = async (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();

    const digits = phoneNumber.replace(/\D/g, "");

    if (digits.length !== 10) {
      return;
    }

    if (!queueCode) {
      setError("Queue information is missing. Please select a queue first.");
      return;
    }

    setError("");
    setIsLoading(true);
    setIsDemo(false);

    // Format currently accepted by the FastAPI backend.
    const backendPhoneNumber =
      `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;

    try {
      // Register the customer in the selected queue.
      const response = await fetch(
        "http://127.0.0.1:8000/database/customer/add_customer",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            phone_number: backendPhoneNumber,
            queue_code: queueCode,
          }),
        }
      );

      if (!response.ok) {
        throw new Error("Backend request failed");
      }

      const customer = await response.json();

      if (customer.ticket_id == null) {
        throw new Error("Ticket ID missing from backend response");
      }

      // Use the ticket generated by PostgreSQL.
      setTicketNumber(String(customer.ticket_id));
    } catch (error) {
      // Fall back to a dummy ticket for frontend testing without the backend.
      console.warn("Could not register customer. Using mock data.", error);
      setTicketNumber("1");
      // Mark it as demo because customer registration was not confirmed.
      setIsDemo(true);
    }

    setShowConfirmation(true);
    setIsLoading(false);
  };

  const handleViewStatus = () => {
    navigate("/queue-status", {
      state: {
        queueCode,
        ticketNumber,
      },
    });
  };

  const handleCancel = () => {
    navigate("/service-information", {
      state: location.state,
    });
  };

  return (
    <div className="customer-join-details-page">
      <Header />

      <main className="customer-join-details-main">
        <section className="customer-join-details-content">
          <h1 className="customer-join-details-title">
            Join Queue
          </h1>

          <p className="customer-join-details-description">
            Enter your phone number to continue.
          </p>

          <form
            className="customer-join-details-form"
            onSubmit={handleContinue}
          >
            <label
              className="customer-phone-label"
              htmlFor="phone-number"
            >
              Phone Number
            </label>

            <div className="customer-phone-input-wrapper">
              <span className="customer-phone-prefix">
                +1
              </span>

              <input
                className="customer-phone-input"
                id="phone-number"
                name="phone-number"
                type="tel"
                inputMode="numeric"
                value={phoneNumber}
                onChange={handlePhoneChange}
                placeholder="(###) ###-####"
                autoComplete="tel"
                required
              />
            </div>

            <p className="customer-phone-help">
              Used to send an SMS when your turn is approaching.
            </p>

            {error && (
              <p role="alert" style={{ color: "#ff0000", textAlign: "center" }}>
                {error}
              </p>
            )}

            <button
              className="customer-join-details-button"
              type="submit"
              disabled={isLoading}
            >
              {isLoading ? "Joining Queue..." : "Continue"}
            </button>

            <button
              className="customer-join-details-cancel-button"
              type="button"
              onClick={handleCancel}
            >
              Cancel
            </button>
          </form>
        </section>
      </main>

      {showConfirmation && (
        <QueueConfirmationModal
          ticketNumber={ticketNumber}
          onViewStatus={handleViewStatus}
          isDemo={isDemo}
        />
      )}
    </div>
  );
}

export default CustomerJoinDetails;